### ISSUE TITLE
More configuration options on `OsStrParser` (maybe making it a "PathParser`?)

### ISSUE THREAD

**Issue by epage** [aj-bagwell/clio#12]
In mapping click concepts to this library,
- `CachedInput`, `Input` and `Output` line up with [File](https://click.palletsprojects.com/en/8.1.x/api/#click.File)
-  `InputPath` and `OutputPath` sort of line up with [File](https://click.palletsprojects.com/en/8.1.x/api/#click.File) with `lazy = true`
- `InputPath` and `OutputPath` lines up with [Path](https://click.palletsprojects.com/en/8.1.x/api/#click.Path) **but** none of `Path`s config  options.

It seems like Path config options would belong as settings on `OsStrParser` so a user can pass in a custom value parser when the defaults expressed through the types don't quite work

**Comment by aj-bagwell** [comment]
I have finally got round to releasing v0.3 which adds a [ClioPath](https://docs.rs/clio/latest/clio/struct.ClioPath.html) for representing more generic paths. 

As per this great suggestion I added extra validation options to [OsStrParser](https://docs.rs/clio/latest/clio/clapers/struct.OsStrParser.html) for `exists`, `is_file` and `is_dir`.

I also added checking for read/write access to `InputPath` and `OutputPath`.
