### ISSUE TITLE
Feature-gated functionality not marked in docs

### ISSUE THREAD

**Issue by jwodder** [aj-bagwell/clio#6]
Features of this crate that are only present when a certain feature is enabled (e.g., the `Http` variant of `Input`) are currently not displayed in the crate's docs on docs.rs.  This can be fixed by following [these instructions](https://users.rust-lang.org/t/how-to-document-optional-features-in-api-docs/64577/3).

**Comment by aj-bagwell** [comment]
Thanks for the tip, you can now see the [`Http` variant with the nice warning box on docs.rs](https://docs.rs/clio/0.2.6/clio/enum.Input.html#variant.Http).
