### ISSUE TITLE
Clap 4.1.0 compat

### ISSUE THREAD

**Issue by max-sixty** [aj-bagwell/clio#8]
I can look more at this from my end, but wanted to flag this is case you recognized immediately what was happening. We get a `clio` error on upgrading `clap=4.0.30` to `clap=4.1.0`.

Possibly this was a breaking change from the `clap` side? We can raise there if so.

ref https://github.com/PRQL/prql/pull/1494

**Comment by aj-bagwell** [comment]
It looks like [dependabot broke the lock file](https://github.com/PRQL/prql/pull/1494#discussion_r1070253464)  to include two versions of clap, let me know if it is still an issue when the lock file is fixed.

**Comment by max-sixty** [comment]
Thanks a lot @aj-bagwell . Apologies for the false alarm as per the other issue.
